### ISSUE TITLE
Python 3.4 import models

### ISSUE THREAD

**Issue by kaiobrito** [pcraston/django-preventconcurrentlogins#7]
On Python 3.4, always gets an "ImportError: No module named 'models" in the middleware file line 5. This version of Python needs to add a dot(.) for import a file in the same directory.
To fix the problem:

change:
     from models import Visitor
to :
     from .models import Visitor

PS: Sorry for my bad english.

**Comment by pcraston** [comment]
Hi
This was fixed in master a while ago, I've finally pushed a new release to pypi.
